name: affiliateMarketingLp'sReport.yml
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  run_job: LandingPagesAffiliateMarketingTest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python Script
      run: |
        cd C:\Users\Suraj\Desktop\RA-Website\src\test\java\com\tests
        python your_script.py

      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py